// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyChe7PC8y4iR9Qfeadt5yKvz_ekvf_8rjQ',
//     appId: '1:779444777060:web:927d2d320e9dff89ad6f71',
//     messagingSenderId: '779444777060',
//     projectId: 'todo-app-96fff',
//     authDomain: 'todo-app-96fff.firebaseapp.com',
//     storageBucket: 'todo-app-96fff.appspot.com',
//     measurementId: 'G-WEZDM0C1SX',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB0q0wxuFFjG492AisvK139n1D055nuK8w',
//     appId: '1:779444777060:android:21d83a56b2c06b24ad6f71',
//     messagingSenderId: '779444777060',
//     projectId: 'todo-app-96fff',
//     storageBucket: 'todo-app-96fff.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAjIF_xO6AWQjXDtAFTDYMFM-XVO-BkjL8',
//     appId: '1:779444777060:ios:995c32cf38ddaf37ad6f71',
//     messagingSenderId: '779444777060',
//     projectId: 'todo-app-96fff',
//     storageBucket: 'todo-app-96fff.appspot.com',
//     iosBundleId: 'com.example.flutterApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAjIF_xO6AWQjXDtAFTDYMFM-XVO-BkjL8',
//     appId: '1:779444777060:ios:995c32cf38ddaf37ad6f71',
//     messagingSenderId: '779444777060',
//     projectId: 'todo-app-96fff',
//     storageBucket: 'todo-app-96fff.appspot.com',
//     iosBundleId: 'com.example.flutterApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyChe7PC8y4iR9Qfeadt5yKvz_ekvf_8rjQ',
//     appId: '1:779444777060:web:f2abea62c59e8f84ad6f71',
//     messagingSenderId: '779444777060',
//     projectId: 'todo-app-96fff',
//     authDomain: 'todo-app-96fff.firebaseapp.com',
//     storageBucket: 'todo-app-96fff.appspot.com',
//     measurementId: 'G-L9ZJSEDRLL',
//   );
// }
