// // // File generated by FlutterFire CLI.
// // // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// // import 'package:flutter/foundation.dart'
// //     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// // /// Default [FirebaseOptions] for use with your Firebase apps.
// // ///
// // /// Example:
// // /// ```dart
// // /// import 'firebase_options.dart';
// // /// // ...
// // /// await Firebase.initializeApp(
// // ///   options: DefaultFirebaseOptions.currentPlatform,
// // /// );
// // /// ```
// // class DefaultFirebaseOptions {
// //   static FirebaseOptions get currentPlatform {
// //     if (kIsWeb) {
// //       return web;
// //     }
// //     switch (defaultTargetPlatform) {
// //       case TargetPlatform.android:
// //         return android;
// //       case TargetPlatform.iOS:
// //         return ios;
// //       case TargetPlatform.macOS:
// //         return macos;
// //       case TargetPlatform.windows:
// //         return windows;
// //       case TargetPlatform.linux:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions have not been configured for linux - '
// //           'you can reconfigure this by running the FlutterFire CLI again.',
// //         );
// //       default:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions are not supported for this platform.',
// //         );
// //     }
// //   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA8LzdEcEtoRDQMZdRWphtn4U9CaTd-UDk',
//     appId: '1:447967780139:web:cd8ee72a9c9733a2ccb96e',
//     messagingSenderId: '447967780139',
//     projectId: 'app-todolists',
//     authDomain: 'app-todolists.firebaseapp.com',
//     storageBucket: 'app-todolists.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCxlXJECYYCew70D3LyK4plEdU5w6TYt-k',
//     appId: '1:447967780139:android:51a21dd3e949b48cccb96e',
//     messagingSenderId: '447967780139',
//     projectId: 'app-todolists',
//     storageBucket: 'app-todolists.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCh8gpK5EUzJNm0DbvcLEMADcYq4M9Z3Pg',
//     appId: '1:447967780139:ios:7b2030139c6a242fccb96e',
//     messagingSenderId: '447967780139',
//     projectId: 'app-todolists',
//     storageBucket: 'app-todolists.appspot.com',
//     iosBundleId: 'com.example.flutterApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCh8gpK5EUzJNm0DbvcLEMADcYq4M9Z3Pg',
//     appId: '1:447967780139:ios:7b2030139c6a242fccb96e',
//     messagingSenderId: '447967780139',
//     projectId: 'app-todolists',
//     storageBucket: 'app-todolists.appspot.com',
//     iosBundleId: 'com.example.flutterApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyA8LzdEcEtoRDQMZdRWphtn4U9CaTd-UDk',
//     appId: '1:447967780139:web:cfa2a88122642daeccb96e',
//     messagingSenderId: '447967780139',
//     projectId: 'app-todolists',
//     authDomain: 'app-todolists.firebaseapp.com',
//     storageBucket: 'app-todolists.appspot.com',
//   );

// // }